  const STAFF=[
   {n:"Alexandra (Lexi) Espinosa",mail:"",loc:"Carlsbad",st:"NM",brand:"FFO",role:"Clinical Asst",team:"Staff"},
   {n:"Cyndal Gomez",mail:"",loc:"Carlsbad",st:"NM",brand:"FFO",role:"Clinical Asst",team:"Staff"},
   {n:"Serenity Gonzales",mail:"",loc:"Carlsbad",st:"NM",brand:"FFO",role:"Clinical Asst",team:"Staff"},
   {n:"Keyly Moran",mail:"",loc:"Carlsbad",st:"NM",brand:"FFO",role:"Front Desk",team:"Staff"},
   {n:"Tayler Nesbit",mail:"",loc:"Carlsbad",st:"NM",brand:"FFO",role:"Clinical Asst",team:"Staff"},
   {n:"Jennifer Peters",mail:"jennifer@farnsworthorthodontics.com",loc:"Carlsbad",st:"NM",brand:"FFO",role:"TC/Financial Coord",team:"Staff"},
   {n:"Lily Rico",mail:"lily@farnsworthorthodontics.com",loc:"Carlsbad",st:"NM",brand:"FFO",role:"OM/Clinic Lead",team:"Staff"},
   {n:"Alyssa Smith",mail:"",loc:"Carlsbad",st:"NM",brand:"FFO",role:"Clinical Asst/Mktg Liason",team:"Staff"},
   {n:"Macayla Villegas",mail:"",loc:"Carlsbad",st:"NM",brand:"FFO",role:"Clinical Asst",team:"Staff"},
   {n:"Mia Armenta",mail:"",loc:"Hobbs",st:"NM",brand:"FFO",role:"Clinical Asst",team:"Staff"},
   {n:"Pamela Hernandez",mail:"",loc:"Hobbs",st:"NM",brand:"FFO",role:"Clinic Lead",team:"Staff"},
   {n:"Linda Herrera",mail:"",loc:"Hobbs",st:"NM",brand:"FFO",role:"Clinical Asst",team:"Staff"},
   {n:"Lucero Holguin",mail:"",loc:"Hobbs",st:"NM",brand:"FFO",role:"Front Desk/Mrkg Liason",team:"Staff"},
   {n:"Hannah Lanier",mail:"",loc:"Hobbs",st:"NM",brand:"FFO",role:"Clinical Asst",team:"Staff"},
   {n:"Melissa Medina",mail:"",loc:"Hobbs",st:"NM",brand:"FFO",role:"Front Desk/Mktg Liason",team:"Staff"},
   {n:"Maria Pando",mail:"",loc:"Hobbs",st:"NM",brand:"FFO",role:"Clinical Asst",team:"Staff"},
   {n:"Elizabeth Reyes",mail:"liz@farnsworthorthodontics.com",loc:"Hobbs",st:"NM",brand:"FFO",role:"TC",team:"Staff"},
   {n:"Yessenia Romaniz",mail:"yessenia@farnsworthorthodontics.com",loc:"Hobbs",st:"NM",brand:"FFO",role:"OM/Clincal Asst",team:"Staff"},
   {n:"Dr. Carla Coehlo",mail:"",loc:"",st:"",brand:"",role:"Associate Doctor",team:"Staff"},
   {n:"Rebecca Fluhman",mail:"becca@farnsworthorthodontics.com",loc:"Lubbock",st:"TX",brand:"FFO",role:"OM/TC",team:"Staff"},
   {n:"Shayna Garza",mail:"",loc:"Lubbock",st:"TX",brand:"FFO",role:"Clinic Lead",team:"Staff"},
   {n:"Melissa Hernandez",mail:"",loc:"Lubbock",st:"TX",brand:"FFO",role:"Clinical Asst",team:"Staff"},
   {n:"Elizabeth James",mail:"",loc:"Lubbock",st:"TX",brand:"FFO",role:"Front Desk",team:"Staff"},
   {n:"Lluvia Lujan",mail:"",loc:"Lubbock",st:"TX",brand:"FFO",role:"Clinical Asst/Mktg Liason",team:"Staff"},
   {n:"Karen Qualls",mail:"karen@farnsworthorthodontics.com",loc:"Lubbock",st:"TX",brand:"FFO",role:"Financial Coord/Front Desk",team:"Staff"},
   {n:"Patricia Tidwell",mail:"",loc:"Lubbock",st:"TX",brand:"FFO",role:"Clinical Asst",team:"Staff"},
   {n:"Dr. Susan McBeth",mail:"drmcbeth@ffortho.com",loc:"",st:"",brand:"",role:"Associate Doctor",team:"Staff"},
   {n:"Monika Flores-Aleman",mail:"",loc:"Clovis",st:"NM",brand:"FFO",role:"Clinic Lead",team:"Staff"},
   {n:"Maria Honorato",mail:"",loc:"Clovis",st:"NM",brand:"FFO",role:"Front Desk",team:"Staff"},
   {n:"Yulissa Martinez",mail:"",loc:"Clovis",st:"NM",brand:"FFO",role:"Clinical Asst",team:"Staff"},
   {n:"Ashley Rodriguez",mail:"",loc:"Clovis",st:"NM",brand:"FFO",role:"Clinical Asst",team:"Staff"},
   {n:"Latricia Sanchez",mail:"latricia@farnsworthorthodontics.com",loc:"Clovis",st:"NM",brand:"FFO",role:"OM/TC/Financial Coord",team:"Staff"},
   {n:"Idaly Tarango",mail:"",loc:"Clovis",st:"NM",brand:"FFO",role:"Front Desk",team:"Staff"},
   {n:"Rebekah White",mail:"",loc:"Clovis",st:"NM",brand:"FFO",role:"Clinical Asst/Mktg Liason",team:"Staff"},
   {n:"Cacy Briseno",mail:"",loc:"San Angelo",st:"TX",brand:"FFO",role:"Front Desk",team:"Staff"},
   {n:"Lyndsey Dunn",mail:"",loc:"San Angelo",st:"TX",brand:"FFO",role:"Clinical Asst",team:"Staff"},
   {n:"Klorissa Garcia",mail:"",loc:"San Angelo",st:"TX",brand:"FFO",role:"Clinic Lead",team:"Staff"},
   {n:"Alicyn \"Haley\" Gossett",mail:"haley@farnsworthorthodontics.com",loc:"San Angelo",st:"TX",brand:"FFO",role:"OM/Clinical Asst",team:"Staff"},
   {n:"Elizabeth \"Liz\" Guerrero",mail:"",loc:"San Angelo",st:"TX",brand:"FFO",role:"Front Desk/Records Tech",team:"Staff"},
   {n:"Samantha Molina",mail:"",loc:"San Angelo",st:"TX",brand:"FFO",role:"Clinical Asst",team:"Staff"},
   {n:"Arianna Peacock",mail:"",loc:"San Angelo",st:"TX",brand:"FFO",role:"Clinical Asst",team:"Staff"},
   {n:"Melinda Tavarez",mail:"melinda@farnsworthorthodontics.com",loc:"San Angelo",st:"TX",brand:"FFO",role:"TC/Financial Coord",team:"Staff"},
   {n:"Amanda Vasquez",mail:"",loc:"San Angelo",st:"TX",brand:"FFO",role:"Clinical Asst",team:"Staff"},
   {n:"Heather Beal",mail:"heather@farnsworthorthodontics.com",loc:"",st:"",brand:"",role:"COO",team:"Staff"},
   {n:"Selene Brown",mail:"selene@farnsworthorthodontics.com",loc:"",st:"",brand:"",role:"Marketing Director",team:"Staff"},
   {n:"Jessica Lynch",mail:"jessica@ffortho.com",loc:"",st:"",brand:"",role:"CSO",team:"Staff"},
   {n:"Brenda Garcia",mail:"",loc:"Mansfield",st:"TX",brand:"Sunflower",role:"Clinical Asst",team:"Staff"},
   {n:"Kandace Lain",mail:"",loc:"Mansfield",st:"TX",brand:"Sunflower",role:"Clinic Lead",team:"Staff"},
   {n:"Erika Munoz",mail:"",loc:"Mansfield",st:"TX",brand:"Sunflower",role:"Clinical Asst",team:"Staff"},
   {n:"Kim Partee",mail:"",loc:"Mansfield",st:"TX",brand:"Sunflower",role:"Clinical Asst/Mktg Liason",team:"Staff"},
   {n:"Noemi Sanchez Torres",mail:"noemi@sunflowerorthomansfield.com",loc:"Mansfield",st:"TX",brand:"Sunflower",role:"OM/TC",team:"Staff"},
   {n:"Tierney Whitesel",mail:"tierney@sunflowerorthomansfield.com",loc:"Mansfield",st:"TX",brand:"Sunflower",role:"Front Desk/Financial Coord",team:"Staff"},
   {n:"Sirena Zamudio",mail:"",loc:"Mansfield",st:"TX",brand:"Sunflower",role:"Front Desk",team:"Staff"},
   {n:"Karin Alons",mail:"",loc:"Las Cruces",st:"NM",brand:"FFO",role:"Clinical Asst",team:"Staff"},
   {n:"Suzy Brown",mail:"suzy@fortholascruces.com",loc:"Las Cruces",st:"NM",brand:"FFO",role:"OM/Clinic Lead",team:"Staff"},
   {n:"Michelle Eichleberger",mail:"",loc:"Las Cruces",st:"NM",brand:"FFO",role:"Front Desk",team:"Staff"},
   {n:"Melissa Elliott",mail:"",loc:"Las Cruces",st:"NM",brand:"FFO",role:"Clinical Asst",team:"Staff"},
   {n:"Cindy Peterson",mail:"cindy@fortholascruces.com",loc:"Las Cruces",st:"NM",brand:"FFO",role:"TC/Financial Coord",team:"Staff"},
   {n:"Roma Powell",mail:"",loc:"Las Cruces",st:"NM",brand:"FFO",role:"Front Desk",team:"Staff"},
   {n:"Yvonne Avalos",mail:"",loc:"Las Cruces",st:"NM",brand:"LCO",role:"Clinical Asst",team:"Staff"},
   {n:"Yessenia Flores",mail:"",loc:"Las Cruces",st:"NM",brand:"LCO",role:"Front Desk",team:"Staff"},
   {n:"Maria Hinojos",mail:"",loc:"Las Cruces",st:"NM",brand:"LCO",role:"Clinical Asst",team:"Staff"},
   {n:"Erica Martinez",mail:"",loc:"Las Cruces",st:"NM",brand:"LCO",role:"Clinical Asst",team:"Staff"},
   {n:"Anette Olvera",mail:"",loc:"Las Cruces",st:"NM",brand:"FFO/LCO",role:"Clinical Asst",team:"Staff"},
   {n:"Tara Pacini",mail:"",loc:"Las Cruces",st:"NM",brand:"LCO",role:"Clinical Asst",team:"Staff"},
   {n:"Joemily \"Emmy\" Prieto",mail:"",loc:"Las Cruces",st:"NM",brand:"LCO",role:"Front Desk",team:"Staff"},
   {n:"Melissa Villalva",mail:"melissa@lascrucessmiles.com",loc:"Las Cruces",st:"NM",brand:"LCO",role:"TC",team:"Staff"},
   {n:"Jenny Whitefield",mail:"jenny@lascrucessmiles.com",loc:"Las Cruces",st:"NM",brand:"LCO",role:"OM/Clincal Asst",team:"Staff"},
   {n:"Dr. David Farnsworth",mail:"",loc:"",st:"",brand:"",role:"Owner/Doctor",team:"Staff"},
   {n:"Dr. Jae Brimhall",mail:"drbrimhall@farnsworthorthodontics.com",loc:"",st:"",brand:"",role:"Owner/Doctor",team:"Staff"}
  ];